### ISSUE TITLE
Trouble with FOS Splitter when window size is changed.Uncaught Error: Splitter needs to be in a component with size

### ISSUE THREAD

**Issue by havvafatmaozbay** [foex-open-source/fos-splitter#4] opened 2022-05-04 14:35 UTC
Hello everyone, I have an issue with FOS Splitter Plug-In.  I have a region which is static content and in the sub region of that region I have FOS-Splitter Plug-In and in the splitter I have 2 interactive gridsWhen I collapse the page I got the error ‘interactiveGrid.min.js?v=21.2.1:5 Uncaught Error: Splitter needs to be in a component with size’ this error on the console. Is anyone know that problem? I mean when window size is changed I faced with this issue and still could not fixed it.

**Comment by mnolan866** [comment] 2022-05-04 14:42
Can you please create a test case on apex.oracle.com and provide access details so we can investigate your issue. Thanks

**Comment by ErickInformatica** [comment] 2022-06-17 15:52
I have the same issue. When size of page change, show this error on the console.
![image](https://user-images.githubusercontent.com/36520780/174333330-c5f28251-184d-4b27-941a-c07e2b0ae7eb.png)

**Comment by mnolan866** [comment] 2022-06-20 08:51
The issue is caused by a zero height being determined on the parent element being split.

Can you please create a test case on apex.oracle.com and provide access details so we can investigate your issue. Thanks

**Comment by havvafatmaozbay** [comment] 2022-08-16 12:22
> The issue is caused by a zero height being determined on the parent element being split.
> 
> Can you please create a test case on apex.oracle.com and provide access details so we can investigate your issue. Thanks

Hello I made a test case on apex 
Workspace name = SPLITTERDEMO
Username = havvafatma45@gmail.com
PW = Fatma97!

App Info 
Username = havvafatma45@gmail.com
PW = Fatma97!
Can you please check what I did wrong? I used region display selector and tab splitter. When I am on the other tabs (the one that is not with tab splitter) and I change the size of the page I get splitter error. Thank you in advance

**Comment by havvafatmaozbay** [comment] 2022-08-16 12:23
![image](https://user-images.githubusercontent.com/56933430/184878727-2ed1e19b-b343-416a-a0b9-7d28e332ac3d.png)

**Comment by foex-open-source** [comment] 2022-08-18 11:29
Thanks for the test case!

You didn't do anything wrong, it's a bug ( related to the "tabs container" ), it'll be fixed with the next release.

(We updated the plug-in in your application, so that should work just fine for now).

**Comment by havvafatmaozbay** [comment] 2022-08-18 11:32
> Thanks for the test case!
> 
> You didn't do anything wrong, it's a bug ( related to the "tabs container" ), it'll be fixed with the next release.
> 
> (We updated the plug-in in your application, so that should work just fine for now).

Thank you so much!

**Comment by ErickInformatica** [comment] 2022-08-18 18:36
I have a similar issue. I want to place tabs on the right side of the splitter. But when an interactive report is placed anywhere it throws the issue.

In this workspace is the demo.


WORKSPACE NAME: PRUEBAS-EBRAN
USERNAME: 27997erick@gmail.com
PASS: P@SSWO4D!

![image](https://user-images.githubusercontent.com/36520780/185468448-cb06cd23-c197-4b63-a476-97d6f0a5f3a1.png)

**Comment by havvafatmaozbay** [comment] 2022-08-26 08:05
> Thanks for the test case!
> 
> You didn't do anything wrong, it's a bug ( related to the "tabs container" ), it'll be fixed with the next release.
> 
> (We updated the plug-in in your application, so that should work just fine for now).

Hi again! We have APEX with version 21.2.1. How can I transfer the solution to our system can you please help me?

**Comment by foex-open-source** [comment] 2022-10-05 21:39
Fixed with v22.1!

**Closed as completed by foex-open-source** 2022-10-05 21:39 UTC
