### ISSUE TITLE
Reducing pane size is tough when the reducing region contains a PDF viewer

### ISSUE THREAD

**Issue by APEXGru** [foex-open-source/fos-splitter#2] opened 2021-06-14 08:17 UTC
We use the splitter to present a form on the left side and a representation of a PDF on the right side (see attached image).
Increasing the PDF part and thus decreasing the form section works like a charm. But decreasing the PDF region is hard - it seems to have difficulties with continuously (re)rendering the view. Is there a solution for this? Maybe some kind of debounce? Maybe Implementing (re)rendering when you release your mouse - or after x seconds - as an option?

![Screenshot 2021-06-14 at 10 13 36 ](https://user-images.githubusercontent.com/17565459/121860546-3d29ba80-ccf9-11eb-87f3-d64c4597f95a.png)

**Comment by mnolan866** [comment] 2021-07-08 19:39
For anyone who has a similar issue, this is caused by capture of focus by the iframe within the panel on the right side of the splitter. The workaround is to add the following CSS to your page

`.a-Splitter-barH.is-active ~ .fos-Splitter-region {
  pointer-events : none;
}`

We will be including this fix in the next FOS 21.1 release due out soon.

**Comment by foex-open-source** [comment] 2021-07-15 13:41
Fixed in just published v21.1.0

**Closed as completed by foex-open-source** 2021-07-15 13:41 UTC
